// =========================================================================
// CPA Canada AI assistant — streaming chat endpoint.
//
//   POST /api/chat  { message, persona, history }
//   → streamed text/plain response, token by token.
//
// Pipeline:  rate-limit  →  cache lookup  →  retrieve context  →  stream answer
//
// When ANTHROPIC_API_KEY is set, answers are generated by Claude with the
// retrieved CPA content as grounding context. Without a key, the same retrieved
// snippets are synthesized into an answer and streamed from the server, so the
// endpoint is fully functional in the demo with no external dependency.
// =========================================================================

import Anthropic from "@anthropic-ai/sdk";
import { retrieve, type Chunk } from "@/lib/retrieval";
import { PERSONAS } from "@/lib/data";

export const runtime = "nodejs";

// ----- In-memory rate limiter: token bucket per client IP -----
const RATE_LIMIT = 20; // requests
const RATE_WINDOW_MS = 60_000; // per minute
const buckets = new Map<string, { count: number; resetAt: number }>();

function rateLimited(ip: string): boolean {
  const now = Date.now();
  const b = buckets.get(ip);
  if (!b || now > b.resetAt) {
    buckets.set(ip, { count: 1, resetAt: now + RATE_WINDOW_MS });
    return false;
  }
  b.count++;
  return b.count > RATE_LIMIT;
}

// ----- In-memory answer cache (LRU-ish) so repeat questions return instantly -----
const CACHE_MAX = 200;
const cache = new Map<string, string>();

function cacheGet(key: string): string | undefined {
  const v = cache.get(key);
  if (v !== undefined) {
    cache.delete(key); // refresh recency
    cache.set(key, v);
  }
  return v;
}
function cacheSet(key: string, val: string) {
  cache.set(key, val);
  if (cache.size > CACHE_MAX) cache.delete(cache.keys().next().value as string);
}

// ----- Lazy Anthropic client (only when a key is configured) -----
let client: Anthropic | null | undefined;
function getClient(): Anthropic | null {
  if (client === undefined) {
    client = process.env.ANTHROPIC_API_KEY ? new Anthropic() : null;
  }
  return client;
}

function systemPrompt(context: Chunk[], personaLabel: string): string {
  const ctx = context.map((c) => `## ${c.title}\n${c.text}`).join("\n\n");
  return [
    "You are the CPA Canada assistant, embedded on the CPA Canada homepage.",
    `The visitor's selected audience is: ${personaLabel || "general public"}.`,
    "Answer questions about becoming a CPA, membership, free CPD, the CPA Canada Handbook, Tax 360™, and finding a CPA.",
    "Be concise, warm, and practical. Use short paragraphs or bullet points. Ground every answer in the context below; if it isn't covered, say what you do know and suggest where to look.",
    "",
    "# Context (retrieved from CPA Canada content)",
    ctx || "(no specific match found)",
  ].join("\n");
}

// Deterministic fallback answer assembled from the retrieved chunks, used when
// no API key is configured. Streamed from the server just like the live path.
function synthesize(context: Chunk[]): string {
  if (context.length === 0) {
    return "I can help with becoming a CPA, free CPD, the CPA Canada Handbook, tax, membership, or finding a CPA. Could you tell me a little more about what you're looking for?";
  }
  const top = context[0];
  const intro = `Here's what I found on **${top.title}**:\n\n`;
  const seen = new Set<string>();
  const points = context
    .slice(0, 3)
    .map((c) => c.summary.split(/(?<=\.)\s/)[0].trim())
    .filter((s) => s && !seen.has(s) && (seen.add(s), true))
    .map((s) => `• ${s}`)
    .join("\n");
  return `${intro}${points}\n\nWant me to go deeper on any of these?`;
}

async function* claudeTokens(message: string, history: { role: "user" | "bot"; text: string }[], context: Chunk[], personaLabel: string) {
  const c = getClient()!;
  const messages = [
    ...history.slice(-6).map((m) => ({ role: m.role === "bot" ? ("assistant" as const) : ("user" as const), content: m.text })),
    { role: "user" as const, content: message },
  ];
  const stream = c.messages.stream({
    model: "claude-opus-4-8",
    max_tokens: 1024,
    system: systemPrompt(context, personaLabel),
    messages,
  });
  for await (const event of stream) {
    if (event.type === "content_block_delta" && event.delta.type === "text_delta") {
      yield event.delta.text;
    }
  }
}

// Replay a cached or synthesized string as a stream, so the client always sees
// the same token-by-token behavior.
async function* replayTokens(text: string) {
  const parts = text.split(/(\s+)/);
  for (const p of parts) {
    yield p;
    await new Promise((r) => setTimeout(r, 12));
  }
}

export async function POST(req: Request) {
  const ip = req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() || "local";
  if (rateLimited(ip)) {
    return new Response("Rate limit exceeded — please wait a moment and try again.", { status: 429 });
  }

  let body: { message?: string; persona?: string; history?: { role: "user" | "bot"; text: string }[] };
  try {
    body = await req.json();
  } catch {
    return new Response("Invalid request body.", { status: 400 });
  }

  const message = (body.message || "").trim();
  if (!message) return new Response("Empty message.", { status: 400 });

  const personaLabel = PERSONAS.find((p) => p.id === body.persona)?.label ?? "";
  const context = retrieve(message, 4);
  const cacheKey = `${body.persona || "none"}::${message.toLowerCase()}`;

  const encoder = new TextEncoder();
  const stream = new ReadableStream<Uint8Array>({
    async start(controller) {
      try {
        const cached = cacheGet(cacheKey);
        if (cached) {
          for await (const tok of replayTokens(cached)) controller.enqueue(encoder.encode(tok));
          controller.close();
          return;
        }

        let full = "";
        if (getClient()) {
          for await (const tok of claudeTokens(message, body.history || [], context, personaLabel)) {
            full += tok;
            controller.enqueue(encoder.encode(tok));
          }
        } else {
          const answer = synthesize(context);
          for await (const tok of replayTokens(answer)) {
            full += tok;
            controller.enqueue(encoder.encode(tok));
          }
        }
        if (full.trim()) cacheSet(cacheKey, full);
        controller.close();
      } catch (err) {
        controller.enqueue(encoder.encode("\n\n(Sorry — I hit an error generating that response.)"));
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: { "Content-Type": "text/plain; charset=utf-8", "Cache-Control": "no-store" },
  });
}
